export interface AIResponse {
  guidance: string;
  riskLevel: 'low' | 'medium' | 'high';
  riskScore: number;
  threatDetected: boolean;
  recommendedAction: 'sos' | 'contacts' | 'navigate_safe' | 'none';
  isLocal: boolean;
}

export interface ChatMessage {
  role: 'user' | 'model';
  text: string;
}

export function formatSafetyGuidance(guidance: string, riskLevel: 'low' | 'medium' | 'high'): string {
  let cleaned = guidance.trim();

  // Strip robotic prefix headers like "🔴 HIGH RISK", "🟡 MEDIUM RISK", "🟢 LOW RISK" if generated by model
  cleaned = cleaned.replace(/^(?:🔴|🟡|🟢)?\s*(?:HIGH|MEDIUM|LOW)\s+RISK\s*\n*/i, '').trim();

  return cleaned;
}

const LOCAL_RULES: { keywords: string[]; response: Omit<AIResponse, 'isLocal'> }[] = [
  {
    keywords: ['follow', 'following', 'behind me', 'chasing', 'stalker', 'stalking', 'pursuing'],
    response: {
      guidance: `⚠️ I understand. Stay calm and avoid going directly home.

What you should do now:
• Move to a crowded, well-lit public place.
• Do not confront the person.
• Call or message someone you trust.
• Keep your phone accessible.
• If the person continues following you and you feel in immediate danger, use emergency assistance.

Safety Tip:
Stay around other people until you feel safe.

Follow-up:
Are you currently in a crowded place or alone?`,
      riskLevel: 'high',
      riskScore: 85,
      threatDetected: true,
      recommendedAction: 'sos',
    }
  },
  {
    keywords: ['threat', 'threatened', 'weapon', 'gun', 'knife', 'kill', 'hurt', 'attack', 'cornered', 'grabbed', 'assault', 'violence', 'danger'],
    response: {
      guidance: `⚠️ I am right here with you. Please focus on your immediate physical safety and creating distance.

What you should do now:
• Move immediately into an open shop, building, or busy public space.
• Do not engage, argue, or confront the person.
• Keep your phone ready to activate SOS or dial 112.
• Make noise or shout for help if the person continues approaching.
• Contact emergency services or trusted contacts without delay.

Safety Tip:
Physical distance, obstacles, and public witnesses are your best immediate shield.

Follow-up:
Can you safely step into an open store or reach people nearby right now?`,
      riskLevel: 'high',
      riskScore: 95,
      threatDetected: true,
      recommendedAction: 'sos',
    }
  },
  {
    keywords: ['night', 'dark', 'isolated', 'empty street', 'deserted', 'lost', 'no lights', 'walking alone', 'alone at night', 'parking lot', 'alley'],
    response: {
      guidance: `I understand you're navigating an isolated or dark area. Let's make sure you reach your destination securely.

What you should do now:
• Stay on well-lit and populated main roads.
• Avoid dark shortcuts, alleys, and deserted paths.
• Keep your phone accessible in your hand.
• Stay connected with someone you trust until you arrive.

Safety Tip:
Prefer a safer route or nearby public place over an isolated shortcut.

Follow-up:
Are there active streetlights or any open shops along your current path?`,
      riskLevel: 'medium',
      riskScore: 65,
      threatDetected: false,
      recommendedAction: 'navigate_safe',
    }
  },
  {
    keywords: ['cab', 'taxi', 'uber', 'driver', 'wrong turn', 'ride', 'stranger', 'car'],
    response: {
      guidance: `I hear your concern about your ride. Your comfort and safety are always the top priority.

What you should do now:
• Check your route on your own map app to monitor navigation.
• Share your live trip details and location with a trusted contact.
• Keep your hand near the door handle and your phone ready.
• Firmly ask the driver to stop at a well-lit, populated public place if you feel unsafe.

Safety Tip:
Always trust your instincts—you have the right to exit the ride early at any safe, populated location.

Follow-up:
Are you currently on an open street with businesses where the car can pull over safely?`,
      riskLevel: 'medium',
      riskScore: 60,
      threatDetected: false,
      recommendedAction: 'contacts',
    }
  },
  {
    keywords: ['unsafe', 'scared', 'uncomfortable', 'suspicious', 'creepy', 'worried', 'nervous', 'weird'],
    response: {
      guidance: `Trust your intuition—if someone or something feels uncomfortable, it's always best to be cautious.

What you should do now:
• Increase physical distance from anyone acting suspiciously.
• Head steadily toward a well-lit, active public area.
• Call a trusted contact and let them know your location.
• Keep your hands free and your phone readily accessible.

Safety Tip:
Leaving an uncomfortable situation early is always a smart and proactive safety choice.

Follow-up:
Do you see an open establishment or group of people you can move toward?`,
      riskLevel: 'medium',
      riskScore: 60,
      threatDetected: false,
      recommendedAction: 'contacts',
    }
  },
  {
    keywords: ['bus', 'subway', 'train', 'metro', 'transit', 'station', 'stop'],
    response: {
      guidance: `Public transit can feel unsettling when it's quiet. Let's make sure you stay in the safest spot.

What you should do now:
• Move closer to the operator, driver, or active groups of passengers.
• Avoid empty train cars or secluded platform corners.
• Keep your belongings secure and your phone in hand.
• Locate the nearest emergency alarm or emergency stop handle.

Safety Tip:
If anyone makes you feel uncomfortable, switch seats or move to a different compartment at the next stop.

Follow-up:
Are there other commuters in your vehicle, or are you mostly alone?`,
      riskLevel: 'medium',
      riskScore: 50,
      threatDetected: false,
      recommendedAction: 'contacts',
    }
  },
  {
    keywords: ['safe', 'home', 'fine', 'good', 'day', 'daytime', 'routine', 'friends', 'lunch', 'dinner', 'advice', 'tips', 'hello', 'hi', 'hey'],
    response: {
      guidance: `Hello! I'm glad you're checking in. I'm here as your personal safety advisor whenever you need tips or guidance.

What you should do now:
• Maintain general awareness of your surroundings.
• Keep your phone charged and easily reachable.
• Share your general schedule or destination with someone you trust.

Safety Tip:
Staying observant and trusting your intuition is the best everyday safety habit.

Follow-up:
Are you heading out somewhere new or preparing for a specific trip today?`,
      riskLevel: 'low',
      riskScore: 15,
      threatDetected: false,
      recommendedAction: 'none',
    }
  }
];

const DEFAULT_LOCAL_RESPONSE: Omit<AIResponse, 'isLocal'> = {
  guidance: `I am listening and here to support you. Let's make sure you have clear, immediate steps for your situation.

What you should do now:
• Stay alert and aware of your surroundings.
• Keep your phone charged, unlocked, and easily accessible.
• Keep trusted contacts updated if your location or schedule changes.

Safety Tip:
Trust your intuition at all times—head to a public space or use emergency assistance if anything feels off.

Follow-up:
Can you describe a little more about where you are and what is happening around you?`,
  riskLevel: 'low',
  riskScore: 20,
  threatDetected: false,
  recommendedAction: 'none',
};

const GEMINI_MODELS = [
  'gemini-3.6-flash',
  'gemini-3.5-flash-lite',
  'gemini-3-flash-preview',
  'gemini-3.7-flash',
];

export async function getAIResponse(
  userInput: string,
  chatHistory: ChatMessage[],
  locationContext?: { latitude: number; longitude: number }
): Promise<AIResponse> {
  const apiKey = process.env.EXPO_PUBLIC_GEMINI_API_KEY;

  if (!apiKey) {
    // Local Fallback Processing (Clearly labeled as local)
    const lowerInput = userInput.toLowerCase();
    for (const rule of LOCAL_RULES) {
      if (rule.keywords.some(keyword => lowerInput.includes(keyword))) {
        return {
          ...rule.response,
          isLocal: true,
        };
      }
    }
    return {
      ...DEFAULT_LOCAL_RESPONSE,
      isLocal: true,
    };
  }

  const locationText = locationContext
    ? `User's current coordinates: Latitude ${locationContext.latitude.toFixed(4)}, Longitude ${locationContext.longitude.toFixed(4)}.`
    : "User's current coordinates are not available.";

  const systemInstruction = {
    role: 'system',
    parts: [{
      text: `You are SafeHer AI, a specialized Personal Safety Advisor and conversational safety companion for women.
Your role is to understand the user's situation described naturally in their own words and provide personalized, immediate, and practical personal safety advice.
Do NOT act like a rigid risk score calculator or duplicate scenario assessment features. Speak directly, calmly, and attentively with the user as a protective safety advisor.
${locationText}

RESPONSE STRUCTURE FOR "guidance":
Your "guidance" response must strictly contain these 4 sections in order:

1. Empathetic Contextual Understanding (1-2 sentences):
   - Acknowledge what the user is experiencing in a calm, reassuring, and alert manner.
   - For high risk or active threat situations, start with '⚠️ '.
   - Do NOT start with cold robotic labels like "🔴 HIGH RISK". Start with a natural conversational sentence (e.g. "⚠️ I understand. Stay calm and avoid going directly home.").

2. What you should do now:
   - Heading: "What you should do now:"
   - Provide 3 to 5 practical, immediate action steps formatted as bullet points ('• ').
   - Tailor actions directly to the user's specific context (transport, walking alone, being followed, uncomfortable ride, home, etc.).
   - HIGH RISK PROTOCOL: Clearly advise moving immediately to a crowded, well-lit public place, avoiding going directly home, avoiding confrontation, keeping phone accessible, and contacting trusted contacts or emergency support (e.g. 112 or local emergency services).
   - REALISTIC & SAFE: Never give dangerous, confrontational, or unrealistic advice (never advise confronting attackers, running into dark alleys, or escalating conflicts).
   - NO LOCATION HALLUCINATIONS: Do NOT pretend, state, or invent that a specific named place, police station, hospital, or pharmacy is nearby unless verified place data is explicitly provided in the prompt. Always suggest general categories like "a crowded or well-lit public place, open store, restaurant, or business".

3. Safety Tip:
   - Heading: "Safety Tip:"
   - Give 1 short, actionable, memorable safety tip.

4. Follow-up:
   - Heading: "Follow-up:"
   - Ask 1 relevant, useful follow-up question to clarify the user's immediate environment or status and keep the conversation protective (e.g., "Are you currently in a crowded place or alone?", "Can you safely step into an open store nearby?").

BACKGROUND SYSTEM FIELDS (Evaluated for background alerts and safety logic, but risk score is NOT the main textual focus):
- "riskLevel": "low" | "medium" | "high"
- "riskScore": number (0-100)
- "threatDetected": boolean
- "recommendedAction": "sos" | "contacts" | "navigate_safe" | "none"

CRITICAL: You MUST respond ONLY with a valid raw JSON object matching the following schema. No markdown wrapping, no code block backticks (like \`\`\`json). Just the raw JSON string.

Schema:
{
  "guidance": "⚠️ I understand. Stay calm and avoid going directly home.\\n\\nWhat you should do now:\\n• Move to a crowded, well-lit public place.\\n• Do not confront the person.\\n• Call or message someone you trust.\\n• Keep your phone accessible.\\n• If the person continues following you and you feel in immediate danger, use emergency assistance.\\n\\nSafety Tip:\\nStay around other people until you feel safe.\\n\\nFollow-up:\\nAre you currently in a crowded place or alone?",
  "riskLevel": "low" | "medium" | "high",
  "riskScore": number,
  "threatDetected": boolean,
  "recommendedAction": "sos" | "contacts" | "navigate_safe" | "none"
}`
    }]
  };

  // Format chat history for Gemini API
  const contents = chatHistory.map(msg => ({
    role: msg.role === 'user' ? 'user' : 'model',
    parts: [{ text: msg.text }]
  }));

  // Add current user turn
  contents.push({
    role: 'user',
    parts: [{ text: userInput }]
  });

  // Real Gemini API Integration with multi-model resilience
  let lastError: any = null;

  for (const model of GEMINI_MODELS) {
    try {
      const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

      const response = await fetch(endpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents,
          systemInstruction: {
            parts: systemInstruction.parts
          },
          generationConfig: {
            responseMimeType: "application/json",
          }
        })
      });

      if (!response.ok) {
        lastError = new Error(`API error (${model}): ${response.status}`);
        continue; // Try next supported model
      }

      const data = await response.json();
      const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;

      if (!text) {
        lastError = new Error(`Empty response from model ${model}`);
        continue;
      }

      let parsed: Omit<AIResponse, 'isLocal'> | null = null;
      let jsonStr = text.trim();

      if (jsonStr.startsWith('```')) {
        jsonStr = jsonStr.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '').trim();
      }

      try {
        parsed = JSON.parse(jsonStr);
      } catch {
        // Find matching outer curly braces if trailing text or multiple JSON blocks exist
        const firstBrace = jsonStr.indexOf('{');
        if (firstBrace !== -1) {
          let depth = 0;
          let inString = false;
          let escape = false;
          let endIdx = -1;

          for (let i = firstBrace; i < jsonStr.length; i++) {
            const char = jsonStr[i];
            if (escape) {
              escape = false;
              continue;
            }
            if (char === '\\') {
              escape = true;
              continue;
            }
            if (char === '"') {
              inString = !inString;
              continue;
            }
            if (!inString) {
              if (char === '{') depth++;
              else if (char === '}') {
                depth--;
                if (depth === 0) {
                  endIdx = i;
                  break;
                }
              }
            }
          }

          if (endIdx !== -1) {
            try {
              parsed = JSON.parse(jsonStr.substring(firstBrace, endIdx + 1));
            } catch (innerErr) {
              console.warn('Inner JSON parse error:', innerErr);
            }
          }
        }
      }

      if (parsed && parsed.guidance && parsed.riskLevel) {
        return {
          ...parsed,
          guidance: formatSafetyGuidance(parsed.guidance, parsed.riskLevel),
          isLocal: false,
        };
      } else {
        lastError = new Error(`Incomplete JSON schema from model ${model}`);
        continue;
      }
    } catch (err) {
      lastError = err;
    }
  }

  // Clean fallback to Local Rule Engine if all API endpoints fail
  console.warn('Gemini API call failed or rate-limited. Seamlessly falling back to Local Rule Engine.');
  const lowerInput = userInput.toLowerCase();
  for (const rule of LOCAL_RULES) {
    if (rule.keywords.some(keyword => lowerInput.includes(keyword))) {
      return {
        ...rule.response,
        isLocal: true,
      };
    }
  }
  return {
    ...DEFAULT_LOCAL_RESPONSE,
    isLocal: true,
  };
}
